export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'https://db-server-eco-1.onrender.com',
  platformProviderBackendApiBaseUrl: 'https://ecomind-backend-t2nh.onrender.com/api/v1',
  platformProviderCommunityEndpointPath: '/community',
  platformProviderUserEndpointPath: '/user',
  platformProviderFamilyEndpointPath: '/family',
  platformProviderFamilyUserEndpointPath: '/family_user',
  platformProviderFamilyInvitationEndpointPath: '/family_invitation',
  platformProviderFriendEndpointPath: '/friend',
  platformProviderAchievementEndpointPath: '/achievement',
  platformProviderCommunityAchievementEndpointPath: '/community_achievement',
  platformProviderUserAchievementEndpointPath: '/user_achievement',
  platformProviderEventEndpointPath: '/event',
  platformProviderPreferenceEndpointPath: '/preference',
  platformProviderNotificationEndpointPath: '/notification',
  platformProviderUserNotificationEndpointPath: '/user_notification',
  platformProviderRankingEndpointPath: '/ranking',
  platformProviderUserRankingEndpointPath: '/user_ranking',
  platformProviderMinigameEndpointPath: '/minigames',
  platformProviderQuestEndpointPath: '/quests',
  platformProviderActivityEndpointPath: '/activities',
  platformProviderUserQuestEndpointPath: '/quest-users',
  platformProviderUserActivityEndpointPath: '/activity-users',
  platformProviderCollaborativeQuestSessionEndpointPath: '/collaborative-quests',
  platformProviderCollaborativeQuestMemberEndpointPath: '/collaborative-quest-members',
  platformProviderFamilyPlanEndpointPath: '/family-plans',
  platformProviderMinigameAttemptEndpointPath: '/minigame-attempts',
  platformProviderCommunityPostEndpointPath: '/community_post',
  platformProviderPostReactionEndpointPath: '/post_reaction',
  platformProviderCommunityGoalEndpointPath: '/community_goal',
  platformProviderEventRegistrationEndpointPath: '/event_registration',
  platformProviderCosmeticEndpointPath: '/cosmetic',
  platformProviderUserCosmeticEndpointPath: '/user_cosmetic',
  platformProviderMultiplierEndpointPath: '/multiplier',
  platformProviderUserMultiplierEndpointPath: '/user_multiplier',
  platformProviderGemPackageEndpointPath: '/gem_package',
  platformProviderGemPurchaseEndpointPath: '/gem_purchase',
  platformProviderGemMovementEndpointPath: '/gem_movement',

  // Public keys only (safe to expose client-side). Replace with your own live/sandbox keys.
  platformProviderCulqiPublicKey: 'pk_test_Z2WRdxu0EQOGU2Ge',
  platformProviderPaypalClientId: 'AUmHZeDzviWVJj_rnXU_c5wEhRKANH7yy_HFdJVDWxgsc1lX_8xYrfG0NJqLJHynBKAsXy4YsaIzZeh2',
};
