export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'http://localhost:3000',
  platformProviderBackendApiBaseUrl: '/backend-api/api/v1',
  platformProviderCommunityEndpointPath: '/community',
  platformProviderUserEndpointPath: '/user',
  platformProviderFamilyEndpointPath: '/family',
  platformProviderFamilyUserEndpointPath: '/family_user',
  platformProviderFamilyInvitationEndpointPath: '/family_invitation',
  platformProviderFriendEndpointPath: '/friend',
  platformProviderAchievementEndpointPath: '/achievement',
  platformProviderCommunityAchievementEndpointPath: '/community_achievement',
  platformProviderUserAchievementEndpointPath: '/user_achievement',
  platformProviderEventEndpointPath: '/event',
  platformProviderPreferenceEndpointPath: '/preference',
  platformProviderNotificationEndpointPath: '/notification',
  platformProviderUserNotificationEndpointPath: '/user_notification',
  platformProviderRankingEndpointPath: '/ranking',
  platformProviderUserRankingEndpointPath: '/user_ranking',
  platformProviderMinigameEndpointPath: '/minigame',
  platformProviderQuestEndpointPath: '/quest',
  platformProviderActivityEndpointPath: '/activity',
  platformProviderUserQuestEndpointPath: '/quest_user',
  platformProviderUserActivityEndpointPath: '/activity_user',
  platformProviderCollaborativeQuestSessionEndpointPath: '/collaborative_quest_session',
  platformProviderCollaborativeQuestMemberEndpointPath: '/collaborative_quest_member',
  platformProviderMinigameAttemptEndpointPath: '/minigame_attempt',
  platformProviderCommunityPostEndpointPath: '/community_post',
  platformProviderCommunityGoalEndpointPath: '/community_goal',
  platformProviderEventRegistrationEndpointPath: '/event_registration',
  platformProviderCosmeticEndpointPath: '/cosmetic',
  platformProviderUserCosmeticEndpointPath: '/user_cosmetic',
  platformProviderMultiplierEndpointPath: '/multiplier',
  platformProviderUserMultiplierEndpointPath: '/user_multiplier',
  platformProviderGemPackageEndpointPath: '/gem_package',
  platformProviderGemPurchaseEndpointPath: '/gem_purchase',
  platformProviderGemMovementEndpointPath: '/gem_movement',

  // Public keys only (safe to expose client-side). Replace with your own test keys.
  platformProviderCulqiPublicKey: 'pk_test_Z2WRdxu0EQOGU2Ge',
  platformProviderPaypalClientId: 'AUmHZeDzviWVJj_rnXU_c5wEhRKANH7yy_HFdJVDWxgsc1lX_8xYrfG0NJqLJHynBKAsXy4YsaIzZeh2',
};
