export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'http://localhost:3000',
  platformProviderBackendApiBaseUrl: '/backend-api/api/v1',
  platformProviderAuthenticationEndpointPath: '/authentication',
  platformProviderCommunityEndpointPath: '/community/communities',
  platformProviderUserEndpointPath: '/user',
  platformProviderFamilyEndpointPath: '/family',
  platformProviderFamilyUserEndpointPath: '/family_user',
  platformProviderFamilyInvitationEndpointPath: '/family_invitation',
  platformProviderFriendEndpointPath: '/friend',
  platformProviderAchievementEndpointPath: '/achievement',
  platformProviderCommunityAchievementEndpointPath: '/community_achievement',
  platformProviderUserAchievementEndpointPath: '/user_achievement',
  platformProviderEventEndpointPath: '/community/events',
  platformProviderPreferenceEndpointPath: '/preference',
  platformProviderNotificationEndpointPath: '/notification',
  platformProviderUserNotificationEndpointPath: '/user_notification',
  platformProviderRankingEndpointPath: '/ranking',
  platformProviderUserRankingEndpointPath: '/user_ranking',
  platformProviderFamilyRankingEndpointPath: '/family-rankings',
  platformProviderFamilyAchievementEndpointPath: '/family-achievements',
  platformProviderFamilyReportEndpointPath: '/family-reports',
  platformProviderMinigameEndpointPath: '/minigames',
  platformProviderQuestEndpointPath: '/quests',
  platformProviderActivityEndpointPath: '/activities',
  platformProviderUserQuestEndpointPath: '/quest-users',
  platformProviderUserActivityEndpointPath: '/activity-users',
  platformProviderCollaborativeQuestSessionEndpointPath: '/collaborative-quests',
  platformProviderCollaborativeQuestMemberEndpointPath: '/collaborative-quest-members',
  platformProviderFamilyPlanEndpointPath: '/family-plans',
  platformProviderMinigameAttemptEndpointPath: '/minigame-attempts',
  platformProviderCommunityPostEndpointPath: '/community/posts',
  platformProviderCommunityPostRealEndpointPath: '/community/posts',
  platformProviderPostReactionEndpointPath: '/community/post-reactions',
  platformProviderGoalEndpointPath: '/community/goals',
  platformProviderCommunityGoalEndpointPath: '/community/community-goals',
  platformProviderEventRegistrationEndpointPath: '/event_registration',
  platformProviderCosmeticEndpointPath: '/cosmetic',
  platformProviderUserCosmeticEndpointPath: '/user_cosmetic',
  platformProviderMultiplierEndpointPath: '/multiplier',
  platformProviderUserMultiplierEndpointPath: '/user_multiplier',
  platformProviderGemPackageEndpointPath: '/gem_package',
  platformProviderGemPurchaseEndpointPath: '/gem_purchase',
  platformProviderGemMovementEndpointPath: '/gem_movement',

  // Learning module endpoints
  platformProviderEducationalMaterialEndpointPath: '/educational-materials',
  platformProviderMaterialReviewEndpointPath: '/material-reviews',
  platformProviderTutorialEndpointPath: '/tutorials',

  platformProviderCulqiPublicKey: 'pk_test_Z2WRdxu0EQOGU2Ge',
  platformProviderPaypalClientId:
    'AUmHZeDzviWVJj_rnXU_c5wEhRKANH7yy_HFdJVDWxgsc1lX_8xYrfG0NJqLJHynBKAsXy4YsaIzZeh2',
};
