export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'http://localhost:3000/api/v1',
  platformProviderCommunityEndpointPath: '/community',
  platformProviderUserEndpointPath: '/user',
  platformProviderFamilyEndpointPath: '/family',
  platformProviderFamilyUserEndpointPath: '/family_user',
  platformProviderFriendEndpointPath: '/friend',
  platformProviderAchievementEndpointPath: '/achievement',
  platformProviderCommunityAchievementEndpointPath: '/community_achievement',
  platformProviderUserAchievementEndpointPath: '/user_achievement',
  platformProviderEventEndpointPath: '/event',
  platformProviderPreferenceEndpointPath: '/preference',
  platformProviderNotificationEndpointPath: '/notification',
  platformProviderUserNotificationEndpointPath: '/user_notification',
  platformProviderRankingEndpointPath: '/ranking',
  platformProviderUserRankingEndpointPath: '/user_ranking',
  platformProviderMinigameEndpointPath: '/minigame',
  platformProviderQuestEndpointPath: '/quest',
  platformProviderActivityEndpointPath: '/activity',
  platformProviderUserQuestEndpointPath: '/quest_user',
  platformProviderUserActivityEndpointPath: '/activity_user',
  platformProviderMinigameAttemptEndpointPath: '/minigame_attempt'
};
